name: Deploy React App to Ubuntu EC2

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Add SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/test-pankaj.key
          chmod 600 ~/.ssh/test-pankaj.key
          ssh-keyscan -H ${{ secrets.AWS_EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          AWS_EC2_USER: ${{ secrets.SSH_HOST }}
          AWS_EC2_HOST: ${{ secrets.SSH_USER_NAME }}
        run: |
          ssh -i ~/.ssh/deploy_key $AWS_EC2_USER@$AWS_EC2_HOST << 'EOF'
          # Ensure the deployment directory exists
          mkdir -p /home/ubuntu/frontend || exit
          
          # Change to the deployment directory
          cd /home/ubuntu/frontend || exit

          # Fix ownership and permissions
          sudo chown -R $AWS_EC2_USER:$AWS_EC2_USER /home/ubuntu/frontend || exit
          sudo chmod -R u+rwX /home/ubuntu/frontend || exit

          # Configure Git to handle permissions issues
          git config --global --add safe.directory /home/ubuntu/frontend || exit

          # Pull the latest code
          git pull origin main || exit

          # Install dependencies and build the project
          npm install || exit
          npm run build || exit
          pm2 delete react
          pm2 start npm --name "react" -- start
          pm2 restart react
          EOF
